<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-10-14 15:51

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.2.16 on 2024-10-22 18:58

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('numero_factura', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Valor_factura', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=80, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
=======
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('numero_telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('imagen_de_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
<<<<<<< HEAD
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.usuario')),
                ('deporte', models.CharField(max_length=50)),
=======
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('deporte', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
        migrations.CreateModel(
            name='DetalleFact',
            fields=[
                ('facturacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.facturacion')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_usuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EncabezadoFact',
            fields=[
                ('facturacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.facturacion')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('resolucion_fact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
<<<<<<< HEAD
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.usuario')),
=======
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('facturacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.facturacion')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('nombre_usuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
<<<<<<< HEAD
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Elite_Hub.usuario')),
=======
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
                ('deportistas_interes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
<<<<<<< HEAD
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.usuario')),
=======
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='Coloca el nombre de tu empresa', max_length=60)),
<<<<<<< HEAD
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('deportista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deporte_detail', serialize=False, to='Elite_Hub.deportista')),
=======
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('descripcion', models.TextField()),
<<<<<<< HEAD
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.marca')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.deportista')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.patrocinador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.marca')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.deportista')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.patrocinador')),
=======
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('deportista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deporte_detail', serialize=False, to='Elite_Hub.deportista')),
                ('descripcion', models.TextField()),
>>>>>>> b61cb2f1500eee577051c0e31a95bb311c5e6927
            ],
        ),
    ]
