# Generated by Django 4.2.16 on 2024-10-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='deportista',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='deportista',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='contenido',
            name='patrocinador',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.usuario'),
            preserve_default=False,
        ),
    ]
