# Generated by Django 4.2.16 on 2024-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0002_alter_usuario_direccion_alter_usuario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='contendido_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='deporte',
            name='nombre_deporte',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
