# Generated by Django 4.2.16 on 2024-10-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0002_remove_comentarios_deportista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='patrocinador',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_de_perfil',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
