# Generated by Django 4.2.16 on 2024-10-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0003_contenido_contendido_imagen_deporte_nombre_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='deportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deporte_detail', serialize=False, to='Elite_Hub.deportista'),
        ),
    ]
