# Generated by Django 4.2.16 on 2024-10-27 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0004_alter_deporte_deportista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
