# Generated by Django 4.2.16 on 2024-10-27 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0005_alter_deportista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='deportista',
        ),
        migrations.AddField(
            model_name='deporte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='deporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elite_Hub.deporte'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
