# Generated by Django 4.2.16 on 2024-10-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0005_alter_deportista_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='imagen_de_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='pqrsd',
            field=models.CharField(choices=[('peticion', 'Peticion'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('demandas', 'Demandas')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deporte',
            name='deportista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deporte_detail', serialize=False, to='Elite_Hub.deportista'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
