# Generated by Django 4.2.16 on 2024-10-27 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0006_remove_deporte_deportista_deporte_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='id',
        ),
        migrations.AddField(
            model_name='deporte',
            name='deportista',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deporte_detail', serialize=False, to='Elite_Hub.deportista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pqrs',
            name='pqrsd',
            field=models.CharField(choices=[('peticion', 'Peticion'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('demandas', 'Demandas')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='deporte',
            field=models.CharField(max_length=50),
        ),
    ]
