# Generated by Django 4.2.16 on 2024-10-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0009_remove_deporte_nombre_deporte_deporte_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='deportistas_interes',
            field=models.CharField(choices=[('ciclistas', 'Ciclistas'), ('futbolistas', 'Futbolistas'), ('corredores', 'Corredores'), ('nadadores', 'Nadadores')], max_length=100),
        ),
    ]
