# Generated by Django 4.2.16 on 2024-10-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0011_alter_patrocinador_deportistas_interes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='contendido_imagen',
            new_name='contenido_imagen',
        ),
    ]
