# Generated by Django 4.2.16 on 2024-10-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0012_rename_contendido_imagen_contenido_contenido_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='pqrsd',
            new_name='tipo',
        ),
    ]
