# Generated by Django 4.2.16 on 2024-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0013_rename_pqrsd_pqrs_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quienes_soomos', models.CharField(blank=True, max_length=255, null=True)),
                ('politica_tratamientodatos', models.CharField(blank=True, max_length=255, null=True)),
                ('conntactenos', models.CharField(blank=True, max_length=255, null=True)),
                ('terminos_condiciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
