# Generated by Django 4.2.20 on 2025-03-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0004_alter_usuario_imagen_de_perfil'),
        ('Elite_Hub', '0013_rename_pqrsd_pqrs_tipo'),
    ]

    operations = [
    ]
