# Generated by Django 4.2.16 on 2024-11-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0014_parametros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='politica_tratamientodatos',
            new_name='politica_tratamiento_datos',
        ),
        migrations.RenameField(
            model_name='parametros',
            old_name='quienes_soomos',
            new_name='quienes_somos',
        ),
    ]
