# Generated by Django 4.2.20 on 2025-03-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0015_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quienes_somos', models.TextField(blank=True, max_length=900, null=True)),
                ('politica_tratamiento_datos', models.TextField(blank=True, max_length=600, null=True)),
                ('contactenos', models.CharField(blank=True, max_length=255, null=True)),
                ('terminos_condiciones', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='descripcion',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores/'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='asunto',
            field=models.CharField(max_length=1130),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Peticion'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('demanda', 'Demanda')], max_length=120),
        ),
    ]
