# Generated by Django 4.2.16 on 2024-11-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0015_rename_politica_tratamientodatos_parametros_politica_tratamiento_datos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='conntactenos',
            new_name='contactenos',
        ),
    ]
