# Generated by Django 4.2.20 on 2025-04-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0016_parametros_patrocinador_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='nivel_estudios',
            field=models.TextField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
