# Generated by Django 4.2.16 on 2024-11-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0017_alter_pqrs_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='politica_tratamiento_datos',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='quienes_somos',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='terminos_condiciones',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
