# Generated by Django 4.2.20 on 2025-04-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0017_nutricionista_nivel_estudios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_noticia', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('titulo', models.CharField(blank=True, max_length=30)),
                ('texto_noticia', models.TextField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
