# Generated by Django 4.2.16 on 2024-11-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0018_alter_parametros_politica_tratamiento_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametros',
            name='politica_tratamiento_datos',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='quienes_somos',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='terminos_condiciones',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='imagen_de_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores/'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='asunto',
            field=models.CharField(max_length=1130),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Peticion'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('demanda', 'Demanda')], max_length=120),
        ),
    ]
