# Generated by Django 4.2.20 on 2025-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0019_eventos_contenido_fecha_deportista_fecha_marca_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimnonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('descripcion', models.TextField(max_length=255)),
                ('Testimnonios_imagen', models.ImageField(blank=True, null=True, upload_to='testimionios')),
            ],
        ),
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutricionista',
            name='descripcion',
            field=models.CharField(default=312, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
