# Generated by Django 4.2.20 on 2025-05-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0020_testimnonios_marca_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimnonios',
            old_name='Testimnonios_imagen',
            new_name='testimonio_imagen',
        ),
    ]
