# Generated by Django 4.2.20 on 2025-05-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0021_rename_testimnonios_imagen_testimnonios_testimonio_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimnonios',
            new_name='Testimonios',
        ),
    ]
