# Generated by Django 4.2.20 on 2025-05-13 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0022_rename_testimnonios_testimonios'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonios',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
