# Generated by Django 4.2.20 on 2025-07-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elite_Hub', '0024_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='¿Que estas pensando?'),
        ),
    ]
